### ISSUE TITLE
Please add support for ImageGlass 9.0

### ISSUE THREAD

**Issue by d2phap** [moooichido/default-dark#2]
My announcement here: https://github.com/ImageGlass/Theme/issues/12.
Thank you!

**Comment by mdapm9di** [comment]
At your request I have updated default-dark  it is now available for the new version of the application ImageGlass

**Comment by d2phap** [comment]
Thanks! Updated on IG website https://imageglass.org/theme/Default-Dark-Mosqovlu-46
